version: '3'
services:
  mincraft-server:
    container_name: minecraft-server
    image: bomura/docker-minecraft-server
    build: ./server
    ports:
      - 25565:25565
    volumes:
      - ./minecraft-server:/minecraft-server
    restart: unless-stopped
