version: '3'
services:
  minecraft_server_aetherii_1.12.2:
    container_name: minecraft_server_aetherii_1.12.2
    image: docker.io/bomura/docker_minecraft_server:aetherii_1.12.2
    build:
      context: ./server
    ports:
      - 25566:25565
    environment:
      - EULA=
      - OP_USER=
      - _JAVA_OPTIONS="-Xmx1024M"
    volumes:
      - world-aetherii-1.12.2:/minecraft-server/world
    restart: unless-stopped
  minecraft_client_aetherii_1.12.2:
    container_name: minecraft_client_aetherii_1.12.2
    image: docker.io/bomura/docker_minecraft_client:aetherii_1.12.2
    build:
      context: ./client
    volumes:
      - ./client/forge:/minecraft-client/forge
      - ./client/mods:/minecraft-client/mods
    restart: unless-stopped
volumes:
  world-aetherii-1.12.2:
